# This file was generated by GoReleaser. DO NOT EDIT.
cask "ajfs" do
  name "ajfs"
  desc "Snapshot file hierarchy, meta data and hash signatures"
  homepage "https://github.com/andrejacobs/ajfs"
  version "0.0.1-beta1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ajfs"

  on_macos do
    on_intel do
      url "https://github.com/andrejacobs/ajfs/releases/download/v#{version}/ajfs_Darwin_x86_64.tar.gz"
      sha256 "026905a2057256ab92621101a778dadcbba3cf1407976c77e3bfec5cd81458b4"
    end
    on_arm do
      url "https://github.com/andrejacobs/ajfs/releases/download/v#{version}/ajfs_Darwin_arm64.tar.gz"
      sha256 "6041ad54e662d8cf8cd619ca5656df8aed0dd33dae32064c2f0f9e0df5b42fe7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andrejacobs/ajfs/releases/download/v#{version}/ajfs_Linux_x86_64.tar.gz"
      sha256 "8703b7104ee781c0c4af598be39129a3b00d2b98edd2621517b93347283184f9"
    end
    on_arm do
      url "https://github.com/andrejacobs/ajfs/releases/download/v#{version}/ajfs_Linux_arm64.tar.gz"
      sha256 "e08355f73eacac10ca8d90336c9dce5060a3d236163494a8dc8c705805f30dc4"
    end
  end

  # No zap stanza required
end
