# This file was generated by GoReleaser. DO NOT EDIT.
cask "ajfs" do
  name "ajfs"
  desc "Index a file hierarchy with meta data and file signatures so that it can be searched, compared, duplicates found all while being on a different machine"
  homepage "https://github.com/andrejacobs/ajfs"
  version "0.0.1-beta6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ajfs"

  on_macos do
    on_intel do
      url "https://github.com/andrejacobs/ajfs/releases/download/v#{version}/ajfs_Darwin_x86_64.tar.gz"
      sha256 "19fe43796060851c5fd4abc3c5c2d58ab00e710bc17fda5d0cc907c44251152e"
    end
    on_arm do
      url "https://github.com/andrejacobs/ajfs/releases/download/v#{version}/ajfs_Darwin_arm64.tar.gz"
      sha256 "28edafb930cd232b96e5708ccab7d4a8ce5084c78ecffbf680cade5dfb415bcb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andrejacobs/ajfs/releases/download/v#{version}/ajfs_Linux_x86_64.tar.gz"
      sha256 "65c2b5c7be36bcf32e0a06595e1084fde0d8c9bbb370a939ae66a5067a4c27cb"
    end
    on_arm do
      url "https://github.com/andrejacobs/ajfs/releases/download/v#{version}/ajfs_Linux_arm64.tar.gz"
      sha256 "c931e9df77c3414a755300222b6364238c293c6b41e2804c4e7a3e298bea261a"
    end
  end

  # No zap stanza required
end
